services:
  imsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  imsfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "6565:8080"
# docker-compose -f docker-compose.yml -f docker-compose.override.yml up