services:
  imsapi:
    build:
      context: .
      dockerfile: IMS-Backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - db
    networks:
      - ims-network
    restart: always

  imsfrontend:
    build:
      context: .
      dockerfile: IMS/Dockerfile
    depends_on:
      - imsapi
    networks:
      - ims-network
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
  
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: ims
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ims-network

volumes:
  pgdata:
  
networks:
  ims-network:
    driver: bridge  